### ISSUE TITLE
How do I generate the .pkl file under /PerformanceModel/?

### ISSUE THREAD

**Issue by LXY-00001** [Fannxy/NFGen#2]
Hi, I was wondering if it would be possible to replace the addition, multiplication and comparison protocols designed separately instead of the publicly available library to generate piece-wise polynomial functions for complex functions? If so, how can I do it.

**Comment by Fannxy** [comment]
I think in this case you have to add a new code template in [this file](https://github.com/Fannxy/NFGen/blob/main/src/NFGen/CodeTemplet/templet.py) that evaluats the piesewise poly with your own operators.
