### ISSUE TITLE
Using NFGen for default MP-SPDZ

### ISSUE THREAD

**Issue by FriendlyN** [Fannxy/NFGen#3]
Hi,

I recently cloned this repo and had a few small issues and questions while trying it out for MP-SPDZ.

1. To get the `example.py` code working, I had to make a few small changes:
    1. Lines 35 and 36 of the MP-SPDZ fixed-point template at https://github.com/Fannxy/NFGen/blob/main/src/NFGen/CodeTemplet/templet.py use `n` - I believe they should be `m`.
    2. I also had to add `from Compiler import types` to support the `@types.vectorize` annotation.

With these two changes, MP-SPDZ can compile the generated sigmoid. Is this a correct fix?

2. When I run the code with example.py's default settings, it produces an approximation with a final (k, m) of (6, 8), or 8 pieces of degree-6 polynomials. However, I would like to use it for MP-SPDZ's default fixed-point representation, which is a 31-bit value providing 16 bits of resolution. 
If I adjust the `example.py` code to use `f = 16` and `n = 31`, leaving other components unchanged, the resulting approximation has many `coeffA` values that equal `16384.0`, but only values on `[-16384, 16384)` can be converted to fixed-point (not inclusive at the upper bound). 
If I use `f = 16`, `n = 30` instead, the approximation has many `-8192.0` and `8192.0` coefficients and uses ~8500 pieces, though it can be compiled under default MP-SPDZ parameters.
So, I had a few questions:
    1. What would be causing so many maximum coefficients?
    2. Is there a configuration that you would suggest to generate piecewise approximations under the smaller default MP-SPDZ precision?
    3. Or is NFGen designed in such a way that the finer precision is necessary for correct execution and good performance?

Thanks.

**Comment by Fannxy** [comment]
Thank you for your interest in NFGen!

Firstly, NFGen utilizes two factors (enlarged coefficient (`coeffA`) and a scaling factor (`scaler`)) to approximate one polynomial coefficient for better accuracy. As a result, you may come across many large `coeffA` values. These coefficients are enlarged to preserve as much significant bits as possible. The real polynomial coefficient is actually `coeffA * scaler`.

For the smaller default precision, I suggest relaxing the precision requirement. Currently, NFGen generates the approximation for` 1e-3` relative precision. You can adjust the value of `"tol": 1e-3, # precision config` in the config dictionary to suit your needs.

NFGen tries to satisfy the given precision requirement first and then aims to achieve a balance between orders and pieces. However, it cannot automatically change the precision requirement. Therefore, you can adjust the configuration to find an approximation that suits your needs.

**Comment by Fannxy** [comment]
And i have fixed the problem in the latest commits~ 
Thanks for your comments, are there any other problems?

**Comment by FriendlyN** [comment]
Thanks for the quick response! I do have a few more:

1. The specific problem with `coeffA` is that the generated polynomials can have values on `[-2^(n - f - 1), 2^(n - f - 1)]`, but MP-SPDZ only supports values `[-2^(n - f - 1), 2^(n - f - 1) - 2^(-f)]` in its fixed-point representation - so, when I try to run the generated code, it produces an error in the MP-SPDZ `./compile.py` execution. Is this something that could be easily changed in NFGen?
2. It looks like the generated piecewise approximations use many more segments for inputs less than 0 than for inputs greater than 0 - do you know why this might be the case? See attached for NFGen's graph of two examples, both with `f = 16, n = 30`; the graph with 6 break points was generated with `tol = .1`, and the graph with 4618 breakpoints was generated with `tol = .01`. Since sigmoid is symmetric, I hoped that the piecewise approximation for inputs less than 0 would be as efficient and use as few pieces as the piecewise approximation for inputs greater than zero; is this possible?
![sigmoid-(k,m=3 6)](https://github.com/Fannxy/NFGen/assets/113555063/cef80e7b-c8c5-4f1b-b596-6f5d4a691bfa)
![sigmoid-(k,m=5 4618)](https://github.com/Fannxy/NFGen/assets/113555063/0e2180fc-77c9-4331-8414-fe61198150db)

**Comment by Fannxy** [comment]
For the first problem, the simplest way to avoid it is to set the configed `n` to `n-1` to tight the coefficient ranges to [-2^(n - f - 2), 2^(n - f - 2)]. Currently NFGen only supports symmetric coefficient ranges.
(you can share your compiling error and maybe i can help :) 

For the second problem, as NFGen is designed to satisfy the SRD (Soft Relative Distance) errors, which means it tries to satisfy the relative error when |f(x)| >= \hat{0} while tend to satisfy the absolute error for very small |f(x)| < \hat{0}. This design explains the so many pieces in input range [-7.5, -3.0] in your second picture, as in this range, |sigmoid(x)| >= \hat{0} while very close to zero, causing the relative error very hard to satisfy. In NFGen, this \hat{0} value is the `zero_mask` in the config dict, which is default to 1e-6.  You can enlarge this value to arond 1e-4 or 1e-3, which will let NFGen adapt to use more absolute distance to evaluate, therefore avoiding the too-many-pieces problem for close-to-zero ranges.

**Comment by FriendlyN** [comment]
Thanks, it took some trying but `zero_mask` and `tol` together were enough to find a good-looking approximation at lower precision!

The specific compiler error when generating with `f=16`, `n=31` and default `tol` and `zero_mask` (generating ~8700 pieces) was:
`Compiler.exceptions.CompilerError: Value out of fixed-point range [-16384, 16384). Use `sfix.set_precision(f, k)` with k being at least f+16`.

It looks like it's specifically a problem when there are a huge number of pieces - so good settings for `tol` and `zero_mask` also prevent this from occurring, because the pieces of the approximation aren't forced to the most extreme values in the space of coefficients searched over.

**Comment by Fannxy** [comment]
Glad to know that~
